services:
  lifx:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3001
      APP_STATE_DIR: /state
    volumes:
      - ./state:/state
